export const repos = [
  {
    id: "auth-module",
    name: "auth-module",
    owner: "gitinsight",
    branch: "main",
    commits: 342,
    prs: 4,
    issues: 6,
    updated: "2h ago",
    status: "Healthy",
    progress: 82,
    language: "TypeScript",
    stars: 1240,
    forks: 89,
    health: 92,
  },
  {
    id: "dashboard-ui",
    name: "dashboard-ui",
    owner: "gitinsight",
    branch: "develop",
    commits: 512,
    prs: 7,
    issues: 12,
    updated: "12m ago",
    status: "Delayed",
    progress: 65,
    language: "TypeScript",
    stars: 830,
    forks: 42,
    health: 74,
  },
  {
    id: "ai-engine",
    name: "ai-engine",
    owner: "gitinsight",
    branch: "main",
    commits: 894,
    prs: 3,
    issues: 2,
    updated: "1h ago",
    status: "Healthy",
    progress: 91,
    language: "Python",
    stars: 2150,
    forks: 210,
    health: 95,
  },
  {
    id: "voice-assistant",
    name: "voice-assistant",
    owner: "gitinsight",
    branch: "feature/wake-word",
    commits: 128,
    prs: 5,
    issues: 9,
    updated: "3h ago",
    status: "Blocked",
    progress: 43,
    language: "TypeScript",
    stars: 420,
    forks: 30,
    health: 58,
  },
  {
    id: "backend-apis",
    name: "backend-apis",
    owner: "gitinsight",
    branch: "main",
    commits: 611,
    prs: 6,
    issues: 4,
    updated: "40m ago",
    status: "Healthy",
    progress: 74,
    language: "Go",
    stars: 980,
    forks: 71,
    health: 84,
  },
  {
    id: "mobile-app",
    name: "mobile-app",
    owner: "gitinsight",
    branch: "release/v2",
    commits: 289,
    prs: 2,
    issues: 5,
    updated: "5h ago",
    status: "Delayed",
    progress: 58,
    language: "Swift",
    stars: 640,
    forks: 55,
    health: 71,
  },
] as const;

export const stats = [
  {
    label: "Repositories",
    value: 12,
    trend: 8,
    icon: "GitBranch",
    spark: [3, 4, 3, 5, 6, 5, 7, 8, 7, 9],
  },
  {
    label: "Commits Today",
    value: 156,
    trend: 12,
    icon: "GitCommit",
    spark: [20, 30, 25, 40, 35, 55, 50, 60, 70, 68],
  },
  {
    label: "Open Issues",
    value: 18,
    trend: -6,
    icon: "CircleAlert",
    spark: [24, 22, 20, 21, 19, 19, 18, 17, 18, 18],
  },
  {
    label: "Open PRs",
    value: 9,
    trend: 4,
    icon: "GitPullRequest",
    spark: [5, 6, 6, 7, 7, 8, 8, 9, 9, 9],
  },
  {
    label: "Active Contributors",
    value: 15,
    trend: 2,
    icon: "Users",
    spark: [10, 11, 12, 12, 13, 14, 14, 15, 15, 15],
  },
  {
    label: "AI Blockers",
    value: 3,
    trend: -1,
    icon: "ShieldAlert",
    spark: [5, 5, 4, 4, 4, 3, 3, 3, 3, 3],
  },
] as const;

export const commitActivity = Array.from({ length: 30 }, (_, i) => ({
  day: `D${i + 1}`,
  commits: Math.round(30 + Math.sin(i / 3) * 20 + Math.random() * 25),
  prs: Math.round(4 + Math.cos(i / 4) * 3 + Math.random() * 3),
}));

export const heatmap = Array.from({ length: 7 }, () =>
  Array.from({ length: 26 }, () => Math.floor(Math.random() * 5)),
);

export const contributors = [
  {
    name: "Durga Rao",
    avatar: "DR",
    commits: 128,
    closed: 42,
    reviews: 61,
    score: 96,
    rating: "A+",
  },
  { name: "Alex Chen", avatar: "AC", commits: 96, closed: 31, reviews: 44, score: 88, rating: "A" },
  {
    name: "Priya Patel",
    avatar: "PP",
    commits: 74,
    closed: 28,
    reviews: 38,
    score: 82,
    rating: "A",
  },
  {
    name: "Marco Rossi",
    avatar: "MR",
    commits: 61,
    closed: 19,
    reviews: 25,
    score: 76,
    rating: "B+",
  },
  { name: "Sara Kim", avatar: "SK", commits: 58, closed: 22, reviews: 30, score: 79, rating: "B+" },
  {
    name: "Liam O'Neil",
    avatar: "LO",
    commits: 42,
    closed: 14,
    reviews: 18,
    score: 68,
    rating: "B",
  },
];

export const blockers = [
  {
    title: "Authentication PR waiting for review",
    priority: "High",
    impact: "Blocks release v2.4",
    fix: "Ping @alex-chen for review; auto-assign backup reviewer.",
    repo: "auth-module",
  },
  {
    title: "Database migration delayed",
    priority: "Medium",
    impact: "Slows dashboard rollout",
    fix: "Split migration into two phases; run backfill overnight.",
    repo: "backend-apis",
  },
  {
    title: "Frontend deployment failed",
    priority: "Critical",
    impact: "Preview environment down",
    fix: "Revert commit `f2a91` and rerun CI on `dashboard-ui`.",
    repo: "dashboard-ui",
  },
];

export const notifications = [
  { title: "New PR opened", desc: "feat(auth): passkey support", time: "2m", type: "pr" },
  {
    title: "Issue assigned to you",
    desc: "Voice wake-word false positives",
    time: "12m",
    type: "issue",
  },
  { title: "Repository synced", desc: "ai-engine · 24 new commits", time: "40m", type: "sync" },
  { title: "AI detected blocker", desc: "Frontend deployment failed", time: "1h", type: "ai" },
  {
    title: "Daily summary ready",
    desc: "Your project digest is available",
    time: "3h",
    type: "summary",
  },
];
